config/routes.rb
Rails.application.routes.draw do
	resources :movies do
		resources :reviews, only: [:new, :create, :destroy]
	end
	resources :moviegoers
	
	root :to  => redirect('/movies')
end

app/models/movie.rb
class Movie < ActiveRecord::Base

	has_many :reviews

	#attr_accessible :title, :rating, :description, :release_date
	def self.all_ratings ; %w[G PG PG-13 R NC-17] ; end #  shortcut: array of strings
	validates :title, :presence => true
	validates :release_date, :presence => true
	validate :released_1930_or_later # uses custom validator below
	validates :rating, :inclusion => {:in => Movie.all_ratings},
		:unless => :grandfathered?

	def released_1930_or_later
    	errors.add(:release_date, 'must be 1930 or later') if
      		release_date && release_date < Date.parse('1 Jan 1930')
	end

	@@grandfathered_date = Date.parse('1 Nov 1968')
	
	def grandfathered?
		release_date && release_date < @@grandfathered_date
	end

  def avg_reviews
		sum = 0
		self.reviews.each do |review|
			sum = sum + review.potatoes
		end
		if self.reviews.count>0
			return sum/self.reviews.count
		else
			return "--"
		end
	end
end

app/models/moviegoer.rb
class Moviegoer < ActiveRecord::Base
	has_many :reviews
	has_many :movies, :through => :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :movie
	belongs_to :moviegoer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/moviegoers_controller.rb
class MoviegoersController < ApplicationController
	def index
		@moviegoers = Moviegoer.all
	end
	
	def show
		id = params[:id]
		@user = Moviegoer.find(id)
	end
	
	def new
		#default rendering
	end
	
	def create
		@user = Moviegoer.create!(params[:user].permit(:name, :provider, :uid))
		flash[:notice] = "#{@user.name} was successfully created."
		redirect_to moviegoers_path
	end
	
	def edit
		id = params[:id]
		@user = Moviegoer.find(id)
	end
	
	def update
		id = params[:id]
		@user = Moviegoer.find(id)
		@user.update_attributes!(params[:user].permit(:name, :provider, :uid))
		flash[:notice] = "#{@user.name} was successfully updated."
		redirect_to moviegoers_path(@user)
	end
	
	def destroy
		id = params[:id]
		@user = Moviegoer.find(id)
		@user.destroy
		flash[:notice] = "#{@user.name} has been deleted."
		redirect_to moviegoers_path
	end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	def index
		@movies = Movie.all
	end
	
	def show
		id = params[:id]
		@movie = Movie.find(id)
	end
	
	def new
		#default rendering
	end
	
	def create
		@movie = Movie.create!(params[:movie].permit(:title, :rating, :description, :release_date))
		flash[:notice] = "#{@movie.title} was successfully created."
		redirect_to movies_path
	end
	
	def edit
		id = params[:id]
		@movie = Movie.find(id)
	end
	
	def update
		id = params[:id]
		@movie = Movie.find(id)
		@movie.update_attributes!(params[:movie].permit(:title, :rating, :description, :release_date))
		flash[:notice] = "#{@movie.title} was successfully updated."
		redirect_to movie_path(@movie)
	end
	
	def destroy
		id = params[:id]
		@movie = Movie.find(id)
		@movie.destroy
		flash[:notice] = "#{@movie.title} has been deleted."
		redirect_to movies_path
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	
	def new
		@users = Moviegoer.all
		#default rendering
	end
	
	def create
		id_movie = params[:movie_id]
		@movie = Movie.find(id_movie)
		id_user = params[:review][:moviegoer_id]
		puts(id_user)
		@user = Moviegoer.find(id_user)
		@review = @movie.reviews.create!(params[:review].permit(:potatoes, :comments, :moviegoer_id))
		flash[:notice] = "A review has from #{@user.name} been successfully added to #{@movie.title}."
		redirect_to movie_path(@movie)
	end
		
	def destroy
		id = params[:id]
		@movie = Movie.find(id)
		@movie.destroy
		flash[:notice] = "#{@movie.title} has been deleted."
		redirect_to movies_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myrottenpotatoes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>

<%= yield %>

</body>
</html>

app/views/moviegoers/_user_form.html.haml
= label :user, :name, 'Username'
= text_field :user, :name
 
= label :user, :provider, 'Provider'
= text_field :user, :provider
 
= label :user, :uid, 'UID'
= text_field :user, :uid

app/views/moviegoers/edit.html.haml
%h2 Edit User
 
= form_tag moviegoer_path(@user), :method => :put do
 
  = render :partial => 'user_form' 

  = submit_tag 'Save Changes'

app/views/moviegoers/index.html.haml
%h1 All Users
 
%table#moviegoers
  %thead
    %tr
      %th Username
  %tbody
    - @moviegoers.each do |user|
      %tr
        %td= user.name
        %td= link_to "More about #{user.name}", moviegoer_path(user)
<br />
#{link_to 'Add new user', new_moviegoer_path} - #{link_to 'Movie list', movies_path}

app/views/moviegoers/new.html.haml
%h2 Create new user
 
= form_tag moviegoers_path, :method => :post do
 
  = render :partial => 'user_form' 
  = submit_tag 'Save Changes'

app/views/moviegoers/show.html.haml
%h2 Details about #{@user.name}
 
%ul#details
  %li
    Provider:
    = @user.provider
  %li
    UID:
    = @user.uid

%h3 Movies reviewed so far
- if @user.reviews.empty?
  %p
    No reviews for this user...
- else
  %ul#details
    - @user.movies.each do |movie|
      %li #{movie.title}

<br /><br />
#{link_to 'Edit info', edit_moviegoer_path(@user)} - #{link_to 'Delete', moviegoer_path(@user), :method => :delete} - #{link_to 'Back to user list', moviegoers_path}

app/views/movies/_movie_form.html.haml
= label :movie, :title, 'Title'
= text_field :movie, :title
 
= label :movie, :rating, 'Rating'
= select :movie, :rating, ['G','PG','PG-13','R','NC-17']
 
= label :movie, :release_date, 'Released On'
= date_select :movie, :release_date

app/views/movies/edit.html.haml
%h2 Edit Movie
 
= form_tag movie_path(@movie), :method => :put do
 
  = render :partial => 'movie_form' 

  = submit_tag 'Save Changes'

app/views/movies/index.html.haml
%h1 All Movies
 
%table#movies
  %thead
    %tr
      %th Movie Title
      %th Rating
      %th Vote (reviews)
      %th Release Date
      %th More Info
  %tbody
    - @movies.each do |movie|
      %tr
        %td= movie.title
        %td= movie.rating
        %td #{movie.avg_reviews} (#{movie.reviews.count})
        %td= movie.release_date
        %td= link_to "Details", movie_path(movie)
#{link_to 'Add new movie', new_movie_path} - #{link_to 'User list', moviegoers_path}

app/views/movies/new.html.haml
%h2 Create New Movie
 
= form_tag movies_path, :method => :post do
 
  = render :partial => 'movie_form' 
  = submit_tag 'Save Changes'

app/views/movies/show.html.haml
%h2 Details about #{@movie.title}
 
%ul#details
	%li
		Rating:
		= @movie.rating
	%li
		Released on:
		= @movie.release_date.strftime("%B %d, %Y")

%h3 Description:

%p#description= @movie.description

%h3 Reviews:
- if @movie.reviews.empty?
	%p
		No reviews for this movie...
- else 
	- @movie.reviews.each do |r|
		- u = Moviegoer.find(r.moviegoer_id)
		<b>#{r.potatoes}</b> (<i>#{Moviegoer.find(r.moviegoer_id).name}</i>) #{r.comments} <br />

= link_to 'Add review', new_movie_review_path(@movie)
<br/><br/>

#{link_to 'Edit info', edit_movie_path(@movie)} - #{link_to 'Delete', movie_path(@movie), :method => :delete} - #{link_to 'Back to movie list', movies_path}

app/views/reviews/new.html.haml
%h2 Add a comment

= form_tag movie_reviews_path, :method => :post do

  = label :review, :potatoes, 'Votes'
  = select :review, :potatoes, [1,2,3,4,5]

  = label :review, :comments, 'Comment'
  = text_field :review, :comments

  = label :review, :user, 'User'
  = select :review, :moviegoer_id, @users.map {|u| [u.name,u.id] }
  <br/><br/>
  = submit_tag 'Add review'